sudo: required
dist: trusty

language: go

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

go: 
  - 1.x

env: GO111MODULE=on CGO_ENABLED=0

install:
  - go mod download

script:
  - go build -o example-app ./example
  - go test -v ./...
